### ISSUE TITLE
Repository error?

### ISSUE THREAD

**Issue by FoxieDev** [GreycLab/gmic#1]
What happened to the commit history, tags, etc?
Was there some sort of GitHub issue that required this? The loss of a project's history, commit messages, issues, MRs, etc.. is a huge blow to the project, so I'm sorry to see this loss of yours.

**Comment by dtschump** [comment]
Yes, my fault. I've completely messed up (mainly because I'm still a git novice after all these years!).
I had to delete/recreate the repository from scratch.

**Comment by FoxieDev** [comment]
That's really a shame, losing so much history on a project that's as old as gmic is will seriously impact it.
There is at least a way to still preserve commit history, branches, tags, and a few other bits, assuming anyone else has the repo un-squashed and with all branches/tags/etc intact. I am sure someone in the community has that at hand.

For future reference by the way, deleting and re-creating the repo is never the right approach to a situation like this, it's always recoverable. I've been there, trust me, but reaching out to the community to ask for a hand in sorting things out and correcting any mistake is a way better approach, and shows development and progress, rather than flying in the face of the fundamental principles of FOSS development.

If you want to try and get this sorted, by the way, on Github, up to 90 days after a deletion, you can recover that repository. I'd highly recommend that you do so by following [this link](https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository). I can state just how much the loss of a project's history severely impacts developers want to contribute to it, and users trust of the project.
