### ISSUE TITLE
Tried to download and install G'MIC for Gimp, but respond missing files

### ISSUE THREAD

**Issue by Jessika07** [GreycLab/gmic#11]
I have download the latest stable version of G'MIC for Gimp, but the installer respond with a bunch of missing files.  Then, i downloaded the standalone version of G'MIC and it worked just fine.  I think you should recheck that all files are included into the plug-in version for Gimp.
![Gmic1](https://github.com/GreycLab/gmic/assets/67011561/14744f74-d28e-4049-a8d3-64e430d48d85)

this was one of the missing files...

I am using Windows 11, 64 bits.

**Comment by gwenn56** [comment]
hello I have the same problem with version gimp 2.10.34 rev 2 and 2.10.32 and with gmic lasted dev or exe

![Capture d'écran 2023-08-14 093115](https://github.com/GreycLab/gmic/assets/142207684/4dfe620c-9d47-49f9-a88f-4a721fee1302)

I am using  windows 11 , 64 bits 22H2

**Comment by dtschump** [comment]
This seems to happen indeed with versions of GIMP that are older than 2.10.34 (final). Could you install the latest GIMP version and tell me is that still happens?

**Comment by gwenn56** [comment]
Good morning

yes this also happens with the latest version, I managed to make gmic work by downloading the gmic_3.2.6-qt-win64 version which contains the DLL , I was missing and installing them manually in the gimp plug-ins folder .

**Comment by LcSantos91** [comment]
Mine is 3.2.6 and happens that two dll files are missing: libicuin72 and libpcre2-16-0. Already reinstalled, but the issue persists.

**Comment by gwenn56** [comment]
Hello
You must download the Standalone GUI version which contains all the DLLs.
Uninstall GMIC and all its files then reinstall it and include the missing DLLs in the plug ins folder and open GIMP.
It worked for me

![Capture d'écran 2023-08-15 133422](https://github.com/GreycLab/gmic/assets/142207684/80b965ac-0216-4a47-a6aa-444496862642)

![Capture d'écran 2023-08-15 133156](https://github.com/GreycLab/gmic/assets/142207684/b1a223c7-c4bc-479a-aa00-6a41a81d090c)

**Comment by dtschump** [comment]
OK, it seems that latest release of GIMP does not provide these two DLLs anymore (`libicuin72.dll` and `libpcre2-16-0.dll`), when installed. When I build G'MIC packages, I try to embed the less possible number of DLL files, to avoid having a large archive to download. Now, I think I need to add these two DLLs in the G'MIC installer.
I'll make new binaries for version 3.2.7_pre and see if that fixes the issue.

Thanks for reporting!

**Comment by dtschump** [comment]
I've posted a new installer for the GIMP plug-in, here : https://gmic.eu/files/prerelease/gmic_gimp2.10_win64.exe
It should be OK to use this one with the latest version of GIMP.

**Comment by dtschump** [comment]
I've updated the installer and zip archive for the current stable version (3.2.6).
Links have been updated on the webpage as well.
Fixed.
