### ISSUE TITLE
Feature Request: import_glob_text

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#16]
I would like to have a mixture of import_text and import_glob. Basically, import every files within folder as if it was imported one by one with **it** command. I think G'MIC is useful for even non-image simple files, hence my asking.

Another idea is to have a option for **it** command to import all files within current directory. Best approach is to '*' as a possible argument which implies every files within current directory is to be imported. This can also be extended to other input commands I think.

However, I can do this manually with exec to find all the file names within current directory, and use it command, process them with my command, and export them back. As a matter of fact, I pushed a command on gmic-community to aid on that.

It's not the most wanted feature request, and workarounds do exist, but I'll leave this idea to you anyway.

**Comment by dtschump** [comment]
You can do something as:
~~~~
foo :
  files 0,"*" files=${}
  repeat narg($files) {
    arg0 $>,$files file=${}
    e "- Load '"$file"'."
    it $file
  }
~~~~
