### ISSUE TITLE
the filter Drawn Montage Gives a preview error

### ISSUE THREAD

**Issue by Mariel01** [GreycLab/gmic#18]
I open a homemade template with basic colors, and some photo's in underlaying layers, then I open the filter "Drawn Montage" in G'Mic. 
I get a preview error. It seems something is going wrong in this filter.
I performed the exact same action with the previous version of G'Mic without problems, 
I work with Gimp 2.10.34 (revisie2) and the latest stable version of G'Mic 3.3.1. for Windows. A friend with a Linux computer got the same error.

Hereby a screenshot. 

![Schermafbeelding 2023-11-04 104228](https://github.com/GreycLab/gmic/assets/86775769/1fe4b354-99e1-4e2f-b045-31bfbaa7e370)

**Comment by dtschump** [comment]
Confirmed. Starting investigation...

**Comment by dtschump** [comment]
Fixed with https://github.com/GreycLab/gmic/commit/fdbf6205302b6a90d0612de46183da4cf5f69bce
Filter upload is on its way. In 5 minutes, please try to press the "Update Filter" button, and the fix should be available for you as well.

**Comment by dtschump** [comment]
And BTW, thanks for reporting this issue! :)

**Comment by Mariel01** [comment]
Wow! you're fast :-) It works fine for me now - thank you so much

**Comment by martinichka** [comment]
Thank you @dtschump
