### ISSUE TITLE
Two missing DLL files on Windows with GIMP 2.10.36

### ISSUE THREAD

**Issue by lorenzogatti** [GreycLab/gmic#19]
Version 3.3.1 of the GMIC GIMP plugin on Windows (64 bit) requires **libicudt72**.dll and **libicuuc72**.dll, which it expects to find in the GIMP bin directory. But the new GIMP version, 2.10.36, has **libicudt73**.dll and **libicuuc73**.dll instead. 
I was able to run GMIC by copying libicudt72.dll and libicuuc72.dll from Inkscape 1.3 into C:\Program Files\GIMP 2\bin\ but of course GMIC should be upgraded to the new versions of these DLLs.

**Comment by lorenzogatti** [comment]
A similar problem to issue #2, but this time GMIC has an older DLL version than GIMP.

**Comment by dtschump** [comment]
I've put a new pre-release installer here : https://gmic.eu/files/prerelease/gmic_gimp2.10_win64.exe
I'll probably release the stable version 3.2.2 soon.

**Comment by lorenzogatti** [comment]
Thank you!

**Comment by dtschump** [comment]
FYI, I've just released a new stable release 3.2.2 : 
https://piaille.fr/@gmic/111385831302611348

**Comment by dtschump** [comment]
Fixed, with the new 3.3.2 release.
