### ISSUE TITLE
Error on starting GIMP

### ISSUE THREAD

**Issue by sp4cecat** [GreycLab/gmic#2]
Installed with installer, on Windows 10 64 bit:

https://www.fosshub.com/GMIC.html?dwl=gmic_3.2.3_gimp2.10_win64.exe

Then on starting GIMP:

![image](https://user-images.githubusercontent.com/2126459/234811233-975f5a60-1b9a-4404-93b3-871fa6144f9f.png)

..also:
libicuuc72.dll not found
libpcre2-16-1.dll not found
and then

![image](https://user-images.githubusercontent.com/2126459/234811641-13355f73-ea2a-4284-96c8-58a375d780d3.png)

**Comment by dtschump** [comment]
You need to install latest version of GIMP (currently 2.10.34) that provides these missing .dll (which are not present in previous GIMP versions, as 2.10.32).

**Comment by sp4cecat** [comment]
> 

Ah! Many thanks, need to stop ignoring those update prompts.

**Comment by snoopuk** [comment]
is there any issue with how I've fixed it, basically copying the missing .dll binaries from the standalone version into the plugin version, which seems to have worked/resolved?

**Comment by luzpaz** [comment]
Is this ticket still relevant ?

**Comment by dtschump** [comment]
With the latest version (3.3.3), the installer puts the required .dlls in the plug-in folder.
This issue should be fixed.
