### ISSUE TITLE
Problème dll

### ISSUE THREAD

**Issue by Chrissoude22** [GreycLab/gmic#24]
Bonjour,

Gmic ne s'ouvre pas dans Gimp 2.10.36. Problème de dll : libgcc_s_seh-1.dll 

Merci de vos réponses

**Comment by dtschump** [comment]
Avez vous essayé avec la dernière version du plug-in (3.3.2) ?
Elle installe toutes les dll nécessaires.

**Comment by Chrissoude22** [comment]
BonjourOui j’ai installé la dernière version de G’mic et de Gimp et le problème est toujours le même.Petite question : êtes-vous le David dont nous parlait toujours  Pierre ? Avez vous de ses nouvelles ? Merci de votre réponse Chris SOUDAISLe 18 nov. 2023 à 13:41, David Tschumperlé ***@***.***> a écrit :﻿
Avez vous essayé avec la dernière version du plug-in (3.3.2) ?
Elle installe toutes les dll nécessaires.

**Comment by Chrissoude22** [comment]
Bonjour, je viens d’installer la version 3.3.2 et je constate que la DLL libgcc_s_seh-1.dll n’est pas dans l’archive ni d’ailleurs dans la version 3.3.3 que j’avais installée auparavant. Je ne sais plus que faire car g’mic n’est pas reconnu dans Gimp alors que je retrouve ce greffon dans les préférences Désolée de vous ennuyer avec ce souciChris SOUDAISLe 18 nov. 2023 à 13:41, David Tschumperlé ***@***.***> a écrit :﻿
Avez vous essayé avec la dernière version du plug-in (3.3.2) ?
Elle installe toutes les dll nécessaires.

**Comment by dtschump** [comment]
La .dll est disponible dans cette archive : https://gmic.eu/files/windows/gmic_3.3.2_qt_win64.zip
qui est la version stand-alone de G'MIC-Qt (pas plug-in). Vous pouvez essayer de la copier/coller à l'endroit où se trouve votre plug-in.

Je n'ai pas eu de nouvelles de Pierre depuis un moment. Je n'avais pas vraiment d'autres moyens de le contacter qu'en passant par son salon Discord.

**Comment by Chrissoude22** [comment]
Merci de ces réponses … je vais essayerChris SOUDAISLe 19 nov. 2023 à 13:15, David Tschumperlé ***@***.***> a écrit :﻿
La .dll est disponible dans cette archive : https://gmic.eu/files/windows/gmic_3.3.2_qt_win64.zip
qui est la version stand-alone de G'MIC-Qt (pas plug-in). Vous pouvez essayer de la copier/coller à l'endroit où se trouve votre plug-in.
Je n'ai pas eu de nouvelles de Pierre depuis un moment. Je n'avais pas vraiment d'autres moyens de le contacter qu'en passant par son salon Discord.

**Comment by Chrissoude22** [comment]
BonsoirJ’ai copié et collé la DLL à l’endroit où sont les plugins et là, nouvelle erreur à l’ouverture :  l’application n’a pas réussi à démarrer correctement(0xc000007b). Tant pis j’utiliserais ce Gmic en dehors de Gimp… Merci de votre aide.Chris SOUDAISLe 19 nov. 2023 à 15:52, Chris Le Coadou ***@***.***> a écrit :﻿Merci de ces réponses … je vais essayerChris SOUDAISLe 19 nov. 2023 à 13:15, David Tschumperlé ***@***.***> a écrit :﻿
La .dll est disponible dans cette archive : https://gmic.eu/files/windows/gmic_3.3.2_qt_win64.zip
qui est la version stand-alone de G'MIC-Qt (pas plug-in). Vous pouvez essayer de la copier/coller à l'endroit où se trouve votre plug-in.
Je n'ai pas eu de nouvelles de Pierre depuis un moment. Je n'avais pas vraiment d'autres moyens de le contacter qu'en passant par son salon Discord.

**Comment by dtschump** [comment]
A priori, la dernière version sortie (v.3.3.3) installe l'ensemble des DLL nécessaires pour le bon fonctionnement du greffon G'MIC-Qt. Essayez de voir avec la toute dernière version. Si cela ne fonctionne pas, cela provient probablement d'une installation exotique ou trop ancienne de GIMP.

**Comment by Chrissoude22** [comment]
Bonsoir, et merci beaucoup de votre message.Je viens d’essayer et tout fonctionne parfaitement.Merci encoreBonne soiréeChris SOUDAISLe 22 janv. 2024 à 15:00, David Tschumperlé ***@***.***> a écrit :﻿
A priori, la dernière version sortie (v.3.3.3) installe l'ensemble des DLL nécessaires pour le bon fonctionnement du greffon G'MIC-Qt. Essayez de voir avec la toute dernière version. Si cela ne fonctionne pas, cela provient probablement d'une installation exotique ou trop ancienne de GIMP.
