### ISSUE TITLE
Gimp 2.10.36 doesn't detect Gmic 3.2.6 plugin on Windows 10

### ISSUE THREAD

**Issue by Vitto2704** [GreycLab/gmic#25]
Hi all,
I just downloaded GIMP 2.10.36 and installed it
I downloaded GMIC 3.2.6 plugin for GIMP, uninstalled previous version and run the 3.2.6 installer.
Now, once GIMP is running, in the filters section I can see GMIC but it is gray-ed and does not launch.
Any suggestion?

Note: the previous version with GIMP 2.10.34 used to work fine

Thanks

**Comment by dtschump** [comment]
If it's gray-ed, the plug-in has been recognized.
Just open an image (or put it in RGB mode), and the plug-in entry should be selectable

**Comment by Vitto2704** [comment]
Thank you dtschump; it worked. My fault, I didn't think about this.
