### ISSUE TITLE
How to transfer all the settings from GMic Gimp/ZArt to command line gmic?

### ISSUE THREAD

**Issue by ProgrammingLife** [GreycLab/gmic#258]
I want to apply gmic effects to a video file. If I get it right, Zart can't export into a video file. So I need to transfer all the settings from GMic Gimp/ZArt to command line gmic for processing extracted series of frames. How to transfer all the settings?

**Comment by myselfhimself** [comment]
hello
you could increase the output to verbose in your g'mic qt and look at your command line (which implies you run gimp or zart with a command line)
See:
https://paulsphotopalace.files.wordpress.com/2016/06/iansnr-filter-partii.jpg
(even though the user interface has changed a bit)
then copy the command you see and append it as parameters to the gmic executable in a different command line shell
