### ISSUE TITLE
Multiple numbers within chars issue.

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#26]
As you noticed on the forum, I have figured out how to display characters correctly. However, with the custom command I have made, they don't work well because this example:

```
e {`'é'`}
```
would print multiple numbers. And my **string_permutation**\* family commands do involve sorting characters. And the fact that this prints multiple numbers would lead to complications as my code didn't account for that, and I don't see a easy way to account for that.

**Comment by dtschump** [comment]
That's actually a common issue with UTF-8 strings (or more generally strings with an extended set of character than just ASCII) : It's not that easy to find the number of characters, as a single character can span over multiple bytes.
If you want your command to work with UTF-8 strings, then you'll probably have to write some additional custom functions to be able to determine how many bytes each character of your string takes.
Definitely requires extra-work. See : https://en.wikipedia.org/wiki/UTF-8 to see what rules you have to take into acoount.

**Comment by Reptorian1125** [comment]
So, how do I find the numbers of characters and return indexes of chars into the correct string? The only solution, I can think of to my problem is to do a naive search of array.

**Comment by dtschump** [comment]
You have basically to iterate over all the elements of the string, and determine, for each character, if it has a multi-byte representation (can take 1 to 4 bytes) :

![image](https://github.com/GreycLab/gmic/assets/10114565/d938eb8a-f9bc-4b23-a858-ae89cb310824)

This basically requires some test of the most significant bits in each byte. Not that hard, but not done already in G'MIC.

**Comment by Reptorian1125** [comment]
Okay, so my plan is to bitshift to get into the most significant bits. In decimal, these numbers can be 8,12,14,15. That tells us the numbers of characters there are.  Then convert the numbers into decimal to convert into indexes which represents these characters so that they can be used for UTF-8 string processing in G'MIC. Sounds incredibly inefficient and I don't think this can be hashed easily.

**Comment by Reptorian1125** [comment]
First work: 
```
#@cli utf8_into_char_indexes: string,var_name
#@cli : Convert string representation into char indexes. Global variables are set for convenience. 
utf8_into_char_indexes:
skip "${2=}"
if size('$2') gn=_$2 fi

eval "
 str='$1';
 const size_str=size(str);
 count_of_bit_set=vector(#size_str,0);
 k=pos=0;
 num_of_chars_analyzed=0;
 while(pos!=size_str,
  current_binary=str[num_of_chars_analyzed]>>4;
  !current_binary?(
   ++pos;
   count_of_bit_set[k]=1;
  ):
  current_binary==12?(
   pos+=2;
   count_of_bit_set[k]=2;
  ):
  current_binary==14?(
   pos+=3;
   count_of_bit_set[k]=3;
  ):
  current_binary==15?(
   pos+=4;
   count_of_bit_set[k]=4;
  );
  ++k;
  ++num_of_chars_analyzed;
 );
 set('count_of_bit_set',v2s(count_of_bit_set));
 num_of_chars_analyzed;
 "
```
