### ISSUE TITLE
Lost in Ubuntu

### ISSUE THREAD

**Issue by KodonAth** [GreycLab/gmic#28]
G'MIC asks which Ubuntu. I don't know, I didn't build this box. Also, I need to upgrade my present G'MIC in my GIMP. I have no clues...

**Comment by dtschump** [comment]
In a shell, if you type:
~~~
~$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
~~~
You'll get the current version of Ubuntu installed.
