### ISSUE TITLE
Warp Plugin [Interactive] in version 2.2.4 - slow

### ISSUE THREAD

**Issue by Mininooo** [GreycLab/gmic#3]
Warp Plugin [Interactive] in version 2.2.3 works fine in Photoshop, in the new version 3.2.4 it is very slow in applying changes to the image. The program keeps calculating the process for several minutes for an adjustment that in version 2.23 is done in a few seconds.

Photoshop v23
GmicPlugin_x64 (version that works for me)

**Comment by dtschump** [comment]
I can't test on Photoshop but I've tested G'MIC-Qt for GIMP here on my Ubuntu distro. The "Warp [interactive]" filter works reasonnably well.
The computation time depends on the image resolution, so are you sure you were applying the filter on an images with the same resolution ?

**Comment by Mininooo** [comment]
Hello again and thank you for replying.
The problem is with any image, even a blank one. The error occurs when you press ENTER or ESC for example to indicate that the correction is finished. It stays thinking for minutes.
The warning was in case something had been changed in the code from one version to another or some file that may affect this problem.
For the moment I will use the previous version and I will try the new ones to see if it is solved. 
It may be my old graphic card.

**Comment by dtschump** [comment]
2.2.4 is a quite old version now. Could you re-try with a more recent one (e.g. 3.3.5) ?
Thanks.
