### ISSUE TITLE
fx_vibrance doesn't work well on the command line

### ISSUE THREAD

**Issue by lbalazscs** [GreycLab/gmic#30]
This problem is in version 3.3.2, and can be seen on both Windows and Linux.  fx_vibrance works well for negative strength values, but not for positive values. The problem is the worst if the output is a PNG file, for example:
```
gmic input.png fx_vibrance 1.58 output out.png
```
I noticed that there seems to be some kind of overflow, and if I add the ```cut 0,255``` command as a second command before creating the output file, then it's OK. Vibrance works well in Gimp, probably because Gimp cuts it automatically.

**Comment by dtschump** [comment]
Thanks for your report.
`fx_vibrance` does indeed produce out-of-range values, which is not expected.
Fix is as you suggested : https://github.com/GreycLab/gmic/commit/af9a872d300f3639213eee0e3d536a70a69106df
`stdlib` and Filters have been updated, so `$ gmic update` should let you have the fix.

**Comment by lbalazscs** [comment]
Thank you, it works fine now, after the update!
