### ISSUE TITLE
Not a valid Win32 application 

### ISSUE THREAD

**Issue by LadyNicola** [GreycLab/gmic#336]
Hi. I'm trying to install G'MIC - GREYC's Magic for Image Computing for GIMP. It keeps coming up 

"pspi: LoadLibrary() failed for C:\\Program Files\\GIMP 2\\share\\gimp\\2.0\\filters\\libbrotlicommon.dll: %1 is not a valid Win32 application"

My Gimp is 64 bit and the Filters are 64bit. What am I doing wrong?

**Comment by dtschump** [comment]
You don't need pspi to run G'MIC on GIMP.
How did you install the plug-in ?
