### ISSUE TITLE
G'mic installation to GIMP

### ISSUE THREAD

**Issue by S0ULL355** [GreycLab/gmic#34]
I tried to install either the zip or installer (exe) but I got an error either way. I get the 0xc000007b error via Zips (and installing the pic 2 libs) along with when I try to click the installer I cannot open it at all. I get hit with what is shown in pic 3. I am on Windows 11 build 23H2 version KB5034123
![Screenshot 2024-01-21 043228](https://github.com/GreycLab/gmic/assets/48848185/03a72bab-a115-4d0f-9dc6-1ef3c2fdad89)
![Screenshot 2024-01-21 042300](https://github.com/GreycLab/gmic/assets/48848185/6ad4feef-503b-4158-b76d-679b9993ea99)
![Screenshot 2024-01-21 042335](https://github.com/GreycLab/gmic/assets/48848185/c1c68b57-4059-4635-ba32-8948821e8841)

**Comment by dtschump** [comment]
Apparently, you are trying to execute the plug-in for GIMP.
It cannot be run as a self-contained application, it must be called from GIMP.

**Comment by S0ULL355** [comment]
Ah, okay I thought I had to like...install it idk why. Thank you for
letting me know.
