### ISSUE TITLE
gmic 3.0.1 -  No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by Schamschula** [GreycLab/gmic#360]
When building gmic 3.0.1 under MacPorts (macOS Big Sur) I get the following error:

```
[ 87%] Generating man/gmic.1
LD_LIBRARY_PATH=/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic/work/build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic/work/build/gmic /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic/work/gmic-3.0.1/src/gmic_stdlib.gmic it /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic/work/gmic-3.0.1/src/gmic_stdlib.gmic reference man > /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic/work/build/man/gmic.1
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input custom command file '/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic/work/gmic-3.0.1/src/gmic_stdlib.gmic' (2262 replaced, total: 2261).
[gmic]-0./ Input text-data file '/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic/work/gmic-3.0.1/src/gmic_stdlib.gmic'.tput: No value for $TERM and no -T specified

```
followed by an infinite loop of `tput: No value for $TERM and no -T specified`

I don't see where `tput` is being invoked. This never happened before.

**Comment by Schamschula** [comment]
I worked around this by disabling the man page (hopefully, temporarily).

**Comment by dtschump** [comment]
I believe this is caused by the G'MIC command `shell_cols` which uses `tput` to estimate the number of columns in the current shell.
Commit : https://github.com/dtschump/gmic/commit/52063f08fb6d1e8e33a140c98fedb8d536676888
should disable this feature for MacOS (as I did for Windows as well).

Do you think this will solve your issue?

**Comment by Schamschula** [comment]
That commit did fix it!

See: https://github.com/macports/macports-ports/commit/82644daa56be5bfa1f6996bbe6092e0fcb3b51d1

**Comment by dtschump** [comment]
I'm currently releasing v.3.0.2 of G'MIC, just for information.
