### ISSUE TITLE
Using G'MIC, Windows has some effects not in Linux

### ISSUE THREAD

**Issue by Meemaw823** [GreycLab/gmic#38]
I use the G'MIC plugin in GIMP in Windows and Linux. Exploring the effects, I have noticed that some of the effects listed in Windows are not present in Linux, specifically, in Arrays & Tiles, Loose Photos is missing, and in Artistic, Comic Book and Paint With Brush are missing.

There may be more, but those were just the 3 I noticed first, and was wondering why....

Will these be added to a future update in Linux?

Thanks

**Comment by dtschump** [comment]
That's probably because you are using an older version on Linux, where the filters are not present.
What is the versions of the plug-in you use on Windows and Linux ?

**Comment by Meemaw823** [comment]
OK, sorry. I should have checked the versions before I made the post.
My Linux version is older, but I'm sure my repo will have the newer version
soon.

Thanks,
Pam
