### ISSUE TITLE
Minor bug report

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#39]
I wonder if there's something wrong with parse_cli.

```
C:\Windows\System32>gmic whatis ratio
[gmic]./ Start G'MIC interpreter (v.3.3.4).
fitratio_wh
poweriteration
rep_nearest_ratio
rep_technorobbo_intense_filtration
resize_ratio2d
[gmic]./ End G'MIC interpreter.
```

Pretty sure rep_technorobbo_intense_filtration is not part of it nor poweriteration should be there. But, this is just minor bug, not a urgent one.

**Comment by dtschump** [comment]
All these function names includes the word `ratio` in them, so it's not surprising they appear in the list.

**Comment by Reptorian1125** [comment]
Where is ratio found in 'rep_technorobbo_intense_filtration' or 'poweriteration'?
