### ISSUE TITLE
Can't install G'Mic (Malware Wacatac.B!ml)

### ISSUE THREAD

**Issue by Toonen1988** [GreycLab/gmic#40]
Hello everyone, 

I can't install G'MIC due the fact that my virus scanner automatically delete G'MIC installer because it contain the Trojan Wacatac.B!ml malware. It could be a false positive, but i'm kinda sceptical. Just because I need to accept Wacatac.B!ml before I can use the plugin. Which means, if this is a false positive, I still gives my anti-virus the order to ignore this malware. 

I also tried the zip version but I can't download it at all. The download just fails. 

Can I download a older version through the official website? Because I didn't had this issue a few weeks ago when I installed a older version.

**Comment by dtschump** [comment]
That's obviously a false positive from you antivirus.
Anyway the old installer are there : https://gmic.eu/files/

**Comment by Toonen1988** [comment]
> That's obviously a false positive from you antivirus. Anyway the old installer are there : https://gmic.eu/files/

The  2024-02-19 build works perfect without false positive.

**Comment by dtschump** [comment]
We very often get reports from G'MIC installer detected as a trojan, when it has just been released.
It turns out that the latest version of G'MIC 3.3.5 has been released only a few hours ago (I didn't even have the time to write a post on X/Mastodon about it).

**Comment by Toonen1988** [comment]
> We very often get reports from G'MIC installer detected as a trojan, when a new G'MIC version has just been released. It turns out that the latest version of G'MIC 3.3.5 has been released only a few hours ago (I didn't even have the time to write a post on X/Mastodon about it).

Ah, I hope this issue is getting solved soon. Downloading a older version fix the problem, if people don't wanna mess inside their anti-virus software.

**Comment by dtschump** [comment]
I close this issue, as this seemed to be a detection error from the antivirus.
