### ISSUE TITLE
Flat 3D Torus after export

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#410]
It seems that there's something wrong with obj export using the following command:

```
$ rep_torus surfels3d .5,.5,.5 o torus.obj
```

This is the command to generate a torus:
```rep_torus:
250,250,125,1,"begin(
  const thickness=cut(.5,0,1);
  const half_thickness=thickness/2;
  const middle_section=1-half_thickness;
  const center=(w-1)/2;
  const center_depth=(d-1)/2;
  const thickness_divisor=w/d;
 );
 xc=(x-center)/center;
 yc=(y-center)/center;
 zc=(z-center_depth)/center_depth/thickness_divisor;
 dist=norm(xc,yc);
 direction=atan2(yc,xc);
 x_torus_center=cos(direction)*middle_section;
 y_torus_center=sin(direction)*middle_section;
 nx=xc-x_torus_center;
 ny=yc-y_torus_center;
 norm(nx,ny,zc)<half_thickness;"
```

If you remove the o ...obj part of the code above, you'd get this: 

![image](https://user-images.githubusercontent.com/20409297/186282122-b3d6b818-d1b9-4602-85ab-6126eb5cde5c.png)

The export seem flat:

![image](https://user-images.githubusercontent.com/20409297/186282160-b572eb02-454d-4cbc-b71a-f25ad56f2da3.png)

**Comment by dtschump** [comment]
This has been fixed recently. It was a bug in CImg.h, so please update your 3.1.6_pre binary.

**Comment by Reptorian1125** [comment]
Confirming it works by closing this.
