### ISSUE TITLE
The watermark added by Fourier Watermark cannot be previewed in Fourier Analysis.

### ISSUE THREAD

**Issue by tu-kui** [GreycLab/gmic#414]
The watermark added by Fourier Watermark cannot be previewed in Fourier Analysis.
After applying Fourier Analysis, you can see the watermark added by Fourier Watermark.

In addition, using Fourier Transform can see the watermark added by Fourier Watermark, I don't know if this is normal.

I found this bug in krita5.1.1 using G'MIC-QT for krita - Windows 64 bits - 3.1.4.

**Comment by dtschump** [comment]
Yes, I've seen your post on Krita-Artist, and already fixed it, but the fix will be available only for next version 3.2.0.

Fix : https://github.com/GreycLab/gmic/commit/a2607be8ce0b10e4ff01ce6fd532ea489dbb8b49

**Comment by tu-kui** [comment]
> Yes, I've seen your post on Krita-Artist, and already fixed it, but the fix will be available only for next version 3.2.0.
> 
> Fix : [a2607be](https://github.com/GreycLab/gmic/commit/a2607be8ce0b10e4ff01ce6fd532ea489dbb8b49)

thanks. 😊
