### ISSUE TITLE
New Command Request: spectrum_simplify

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#417]
I would like a command to automatically convert images with the least amount of spectrum without information loss. So, if a image contains RGB with alpha that has zero variance, and every value is 255, then it becomes RGB. Otherwise, if a image has same values within all three RGB, and has alpha with variance, then it becomes GrayA. You get the idea.

**Comment by Reptorian1125** [comment]
Just realized 'to_colormode 0' exist after checking. Thanks for reading, anyway.

**Comment by Reptorian1125** [comment]
Actually, no, it didn't work.

**Comment by dtschump** [comment]
Done with new command `to_automode`:
https://github.com/GreycLab/gmic/commit/375ee5305613735aa5d8e0922d34134d488c7a6b
