### ISSUE TITLE
where is "Easy Skin Retouch" on Gmic?

### ISSUE THREAD

**Issue by reynaldovelazquez** [GreycLab/gmic#426]
thats it, i was used to that filter "easy skin retouch" on Gmic, and now suddenly just dissapeared? i s not where i used to find it... what happened

**Comment by dtschump** [comment]
It is located in **Details/**, still there : 

![gmic_skin_retouch](https://user-images.githubusercontent.com/10114565/218837429-9eb460a7-b336-4d1a-b138-3abd863a8e3d.jpg)
