### ISSUE TITLE
How to use GMIC Artistic/Stylize in newer versions

### ISSUE THREAD

**Issue by artistlibre** [GreycLab/gmic#427]
I have gone through multiple tutorials, but, none of them explains how to use custom image for GMIC Artistic/Stylize plugin. I tried for Krita, GIMP and Natron. Is there any easy way to do this... like opening custom images from folder? Thanks in advance!

![image](https://user-images.githubusercontent.com/103920849/210348424-469c80f0-cc50-40ca-844d-d4214eb285f6.png)

**Comment by 0xC0000054** [comment]
For GIMP the Stylize custom image support is done using layers. If the document has 2 layers you can select the top or bottom layer as the source for the custom style.

Using multiple layers requires the G'MIC-Qt Input Mode option to be set to All, it may do this by default for Stylize but I am not sure.
