### ISSUE TITLE
Slight difference in two images. Unsure if it is a bug though or something else.

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#432]
If you execute this command in cli
```
$ i thispersondoesnotexist.jpg i thispersondoesnotexist.png shared[-1] {s-1} autocrop_coords , rm. crop[-1] ${} channels 0,{s-2}
```
Using the images found in here.

[thispersondoesnotexist.zip](https://github.com/GreycLab/gmic/files/10724529/thispersondoesnotexist.zip)

Then, you'd note that based on statistical information, they're different. Is this the expected result? The .png image is just a extended canvas version of the .jpg image.

Testing via Paint.NET does not show that there's a difference in color information. However, in G'MIC, there is differences.

**Comment by dtschump** [comment]
> The .png image is just a extended canvas version of the .jpg image.

I don't know how you produced these two images, but clearly, the .png file is not just an extension of the .jpg one.
If you used something as
~~~~
gmic portrait +r 2048,2048,1,3,0,0,0.5,0.5 o[0] thispersondoesnotexist.jpg o[1] thispersondoesnotexist.png
~~~~
then no surprise : when you save a .jpg file, you will lose information, as .jpg is a lossy compression format.

**Comment by Reptorian1125** [comment]
It was produced with the fake person generator. Then, open it the jpg in Paint.NET, extend the canvas with [0,0,0,0] while values inside border is [R,G,B,255], then save as .png. There is no successive .jpg save, so information loss isn't there. So, there should be no difference at all, and the test with opening those two image and aligning them together does not show any difference along the R,G,B channels. 

By using Paint.NET, overlaying them and using difference blending mode, finally use Color Curve to set 1 into 255, I get this result:

![image](https://user-images.githubusercontent.com/20409297/218860697-d0bea981-a76e-4bd9-acb6-0ca950dff3b4.png)

**Comment by dtschump** [comment]
Then it must be something weird with Paint.NET.
With G'MIC, if you do the same kind of process:
~~~
$ gmic portrait 1024 o thispersondoesnotexist.jpg rm thispersondoesnotexist.jpg frame 512,512,0 o thispersondoesnotexist.png
~~~
and then you try to reread them and compare:
~~~
$ gmic thispersondoesnotexist.jpg thispersondoesnotexist.png autocrop. -- norm
~~~
You get exactly zero everywhere in the difference image. At least, that's what I get with the latest 3.2.1_pre development version.

**Comment by Reptorian1125** [comment]
Ok, I confirmed that it's a Paint.NET related bug and reported to Rick Brewster. I checked with Krita and confirmed that the jpg and png are definitely different. I know that there's a way to reference bugs elsewhere, so I will close this.
