### ISSUE TITLE
Suggestion, last line in end() in eval should return status.

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#433]
Just as title said. Sometimes, you may want to perform multi-threaded operation on a vector, and return that to status. The workaround is to use set('v',v2s()) or run('status='v2s()). I find that there's a bottleneck for those two lines, but pretty mild, .004 s at minimum or best case. Or maybe it should be as an additional option as in eval "command",last_line_returned_as_status where last_line_returned_as_status treats the very last line value to be set to status. 0 for legacy, and 1 for true.

**Comment by dtschump** [comment]
That's actually a good idea.
I've made modifications in the code so that commands `fill` and `eval` sets the status with the result from the `end()` block (if specified, or status is emptied otherwise).
Will be available for next version 3.2.1.

**Comment by dtschump** [comment]
Finally not a good idea, as an expression such as:
~~~
eval. "x; end(run('u toto'));
~~~
would actually silently set `nan` (the return value of `run()`) as the status, which is absolutely not expected.

**Comment by Reptorian1125** [comment]
Would status() in math parser remedy the issue? As in if it is specified anywhere, math parser sees what line to use status, but at the same time, behaves as if it was without status. If not specified, assume the current behavior of last line outside of end()?

**Comment by dtschump** [comment]
Since 2.3.1, you can use `set('{}',value)` to set the status inside the math parser.
You can also use `get('{}')` and `${}` to get its value.

**Comment by Reptorian1125** [comment]
I think you mean 3.2.1. That being said, I used this on rep_find_factors_of, and it looks better now, thanks.
