### ISSUE TITLE
Resulting names seem to be trimmed

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#434]
For some reason, executing this code results in missing name part or trimmed name.

```
$ 512,512 256,256 512,512 512,512 256,256 256,312 rep_two_dimension_set_indices
```
```
#@cli rep_two_dimension_set_indices:
#@cli : Return images containing indexes
rep_two_dimension_set_indices:
num_of_imgs:=$!

repeat $num_of_imgs {
 width:=w#$>
 height:=h#$>

 if narg(${image_dimension_$width_$height})
  eval da_push(#${image_dimension_$width_$height},$>)
 else
  1 => image_dimension_$width_$height
  eval da_push(#-1,$>)
 fi
}

foreach[$num_of_imgs--1] { eval da_freeze(#-1) }
```
Yet this works fine:
```
$ sp cat "=>" image_dimension_{w}_{h}
```

**Comment by dtschump** [comment]
> ${image_dimension_$width_$height}

Without going further, I would say this kind of expression is suspect.
Because `$_width_$height` is actually equivalent to `${width_}${height}` and not to `${width}_${height}`, as you probably expect.

**Comment by Reptorian1125** [comment]
Thanks, I learned something new today.

**Comment by dtschump** [comment]
That's because the underscore character `_` is a valid character to be used in variable names.
