### ISSUE TITLE
Warp transform error

### ISSUE THREAD

**Issue by muffinn2** [GreycLab/gmic#44]
GMIC v 3.35 in Gimp 2.10.36

Now get an error message 
![image](https://github.com/GreycLab/gmic/assets/79443902/bc2ec4dc-0d75-4ed5-af16-5d0deaf69285)

**Comment by dtschump** [comment]
Fixed with https://github.com/GreycLab/gmic/commit/ef7bf969c0005ae8a2c3cecbd7b062fe7c58edb3
Filters have been updated, press the 'Update filters' button to get the fix.
Thanks for reporting!

**Comment by muffinn2** [comment]
Brilliant! Thanks. What a wonderful response!
Mike
    On Tuesday, 9 April 2024 at 08:27:42 BST, David Tschumperlé ***@***.***> wrote:  
 
 


Fixed with ef7bf96
Filters have been updated, press the 'Update filters' button to get the fix.
Thanks for reporting!
