### ISSUE TITLE
error extracting gmic_cluts.gmz

### ISSUE THREAD

**Issue by vredesbyyrd** [GreycLab/gmic#444]
gmic 3.2.2-1
archlinux 6.2.8-1

Hello, I am trying to extract all the luts from gmic_cluts.gmz, then build a gmz with only handful of luts for use in darktable. 

Within the last year I used the following command for extraction successfully: 

`gmic -i gmic_cluts.gmz -repeat \$!,k -local[\$k] -o "{0,n}".gmz,uchar -endlocal -done`

_Returned error:_ 

`*** Error *** Command 'repeat': Invalid argument '1045,k'; Unrecognized item '1045,k' in expression '1045,k'.`

Any thoughts? Thanks. 

**EDIT:** 

I typed in the wrong gmic command, fixed above command and error

**Comment by dtschump** [comment]
Yes, the syntax has a bit changed in 3.2.2 for the `repeat...done` construct.
Now, you can use the new `foreach...done` syntax, and it should give:
~~~
gmic gmic_cluts.gmz foreach o "{0,n}".gmz,uint8 done
~~~

**Comment by vredesbyyrd** [comment]
That did it. Syntax appears a bit simpler which is nice. 

Thanks for help!
