### ISSUE TITLE
0^0 is equal to 1. Mathematically wrong though.

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#447]
I know this is a quirk of C/C++. As a consequence, it would be a quirk of G'MIC as well.

```
C:\Users\User\Pictures\gmic-qt-data>gmic echo \"[gmic]-0./ \"0"^"0={0"^"0}
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ 0^0=1
[gmic]-0./ End G'MIC interpreter.
```

Maybe this should be fixed.

**Comment by dtschump** [comment]
Why mathematically wrong?

-> https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero

What value would you expect for $0^0$ ?

**Comment by Reptorian1125** [comment]
That state that either it's 1 or undefined. And different languages has different way of handling 0^0. Maybe fix is not needed.

**Comment by dtschump** [comment]
`NaN` could be another returned value indeed, but probably not desired for the general case, as it introduces a discontinuity in the function. And in any case : 
~~~ 
my_pow(a,b) = (!a && !b?nan:a^b);
~~~
does the job.
