### ISSUE TITLE
Image layer goes all black with GIMP filters

### ISSUE THREAD

**Issue by danjosam** [GreycLab/gmic#48]
After applying a GMIC effect like Vibrance, the image layer goes all black if I try to apply the GIMP built-in Blur or Enhance filters after using GMIC effects. I have tried making a copy of the layer by duplicating or making new visible layer, I have exported the image with different settings keeping or converting the color profile to GIMP and nothing seems to fix this issue on my end.

**Comment by dtschump** [comment]
That is really strange!
Could you provide maybe one example image so we can reproduce this issue ?
I've tried with a simple test color image, and it works (Vibrance + GIMP built-in Gaussian Blur).

What's the precision used for your image ? float16 or float32 maybe ?

**Comment by danjosam** [comment]
> That is really strange! Could you provide maybe one example image so we can reproduce this issue ? I've tried with a simple test color image, and it works (Vibrance + GIMP built-in Gaussian Blur).
> 
> What's the precision used for your image ? float16 or float32 maybe ?

Hi, 

I am using Tiff 32bit floating point. How could I provide the example image? Attaching it here in the message? I think Tiff format has a quite large file size to attach it here.

**Comment by dtschump** [comment]
Could you first try just blurring your image with GIMP builtin filter ? (so without using G'MIC at all).
A float32 Tiff file may contains NaN or inf values that may be not managed correctly by GIMP.
Another solution is that the Vibrance filter does create NaN or inf values, but that's not likely to happen.

**Comment by dtschump** [comment]
So really, I suspect your original .tiff file to contain NaN or inf values.
Those values can spread over all the image when using spatial filters like blur (particularly if the blur uses a recursive implementation). I wouldn't be surprised if you tell me that the built-in GIMP blur directly on your image makes it black.
