### ISSUE TITLE
G'MIC 3.3.5 “FRAME [regular]” filter, “frame parameters” section no longer reacts

### ISSUE THREAD

**Issue by mamipi972** [GreycLab/gmic#49]
Hello,

Windows 10
GIMP 2.10.36
G'MIC 3.3.5

In the “FRAME [regular]” filter, the “frame parameters” part no longer reacts in the preview: wight, height, color and outline.

On the other hand, “crop parameters” above works well in the preview and when a new image is output.

By validating

Best regards,
Miguel Pineau
![image](https://github.com/GreycLab/gmic/assets/111678889/eeaff8a0-a94f-41e4-8509-81117c54beb9)

**Comment by dtschump** [comment]
Indeed. Fix has been pushed and updating your filters should let you get the corrected version.
Thanks for reporting!
