### ISSUE TITLE
[JOSS] ambiguous library description

### ISSUE THREAD

**Issue by Smattr** [GreycLab/gmic#53]
The JOSS paper being reviewed at https://github.com/openjournals/joss-reviews/issues/6618 contains the sentence “libgmic and libgmic, respectively C++ and C libraries…” Presumably this is not meant to say the identical text “libgmic” twice?

**Comment by dtschump** [comment]
Right,,the second one should read `libcgmic`.

**Comment by dtschump** [comment]
Fixed with https://github.com/GreycLab/gmic/commit/bd4aac57bdad4a5e237d2655d81736575a4c9b2b
