### ISSUE TITLE
[JOSS] No testing instructions

### ISSUE THREAD

**Issue by jamesrhester** [GreycLab/gmic#57]
JOSS reviewer here. One of the JOSS requirements is clear testing instructions. I couldn't find anything like this in the g'mic repository or docs.

Of course, testing whether an image has changed the way you want it to is a bit hard to automate, so I suggest simply adding a 'Testing' section to the 'Download' page, pointing the user to the "resources/samples" directory of this repository and advising that the user checks that all scripts work (perhaps explaining how to run them).

Or perhaps just running `gmic demo` is sufficient.

**Comment by dtschump** [comment]
That is right. Thanks for pointing this out to me.

Commit https://github.com/GreycLab/gmic/commit/7f75b4658b6ff22121c9ebd3232f0e5aee7f9da2 fixes this, by adding a new section "Testing Features" on the Download page.

![image](https://github.com/GreycLab/gmic/assets/10114565/d9549f52-16cf-4e80-9893-8bf169facae7)

**Comment by jamesrhester** [comment]
That's perfect.
