### ISSUE TITLE
v() bug

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#63]
Just run this code.
```
foo: v:=v(0,192928249295) echo $v
```
It just halts or something. I don't see output of $v, and CPU stays at 8%.

Workaround using int(u(0,192928249295)) works though.

**Comment by Reptorian1125** [comment]
Thanks. Does this mean I will have to use int(u()) workaround?

**Comment by dtschump** [comment]
> Thanks. Does this mean I will have to use int(u()) workaround for larger numbers?

OK, I've extended the functions to generate 64bits random integers.
Commit : https://github.com/GreycLab/CImg/commit/32ae702c3195ff7d700b8253f79cadeb1ec853c3

But please note technically speaking, larger numbers than +-2^32 cannot be considered as integer anymore (cannot be stored in a 64bits integer). So there are no chances you can get accurate random numbers with larger ranges.
