### ISSUE TITLE
Question about find().

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#65]
I know that nan has a issue of comparison, but could find() have a remedy where it actually can find nan, or would the performance tradeoff be not worth it?

I'm using this block of code to check if value exist in the hash table:
```
if(da_size(#key),p=find(#key,i,0,2)+1;)
```
And I find that my recent code **rep_val2order** has issues with nans, which comes down to find().

If it can't be remedied, I'll just make a error code indicating nan detection.

**Comment by Reptorian1125** [comment]
It works if you assign vector directly. Sadly, in a hash table case, it doesn't. 

```
C:\Users\User>gmic (1,2,nan,1,4) echo {find(#-1,nan,1,0)}
[gmic]./ Start G'MIC interpreter (v.3.4.3).
[gmic]./ Input image at position 0, with values (1,2,nan,1,4) (1 image 5x1x1x1).
-1
[gmic]./ Display image [0] = '(1,2,nan,1,4)'.
[0] = '(1,2,nan,1,4)':
  size = (5,1,1,1) [20 b of float32].
  data = (1,2,nan,1,4).
  min = 1, max = 4, mean = nan, std = 0, coords_min = (0,0,0,0), coords_max = (4,0,0,0).
[gmic]./ End G'MIC interpreter.
```

**Comment by dtschump** [comment]
Fixed with https://github.com/GreycLab/CImg/commit/7904da33c164db1cf9dc63f5ddf9fdf48adc3ecd
