### ISSUE TITLE
same() does not account for NaN

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#68]
Thanks for the change you did on _find()_. I think it helps **rep_val2order** work properly with **NaN**s.

**Comment by dtschump** [comment]
This https://github.com/GreycLab/CImg/commit/2b5b82522507f06faeb466abf5ae2f911a902384 should fix this issue.
Anyway, please keep in mind that working with `NaN` values is kind of hazardous, if you need to manage more complex operations (like convolution, resize, etc.). The computational overhead to systematically test for `NaN` value may not worth it.

**Comment by Reptorian1125** [comment]
> The computational overhead to systematically test for `NaN` value may not worth it.

I'm aware of that. I guess, find() could benefit from a optional parameter to check for `NaN` or does not take into account for it given there's more overhead there. But, probably too much work to fix now. But, anyway, thanks. That makes my **rep_mode_blend** command account for `NaN` when there's a `NaN`.
